---
- name: Create a network
  docker_network:
    name: network-10.0.0.0_16
    ipam_config:
      - subnet: 10.0.0.0/16
        gateway: 10.0.0.1

- name: Assign ip address and connect a container to the network
  docker_container:
    name: ubuntu_18.04
    networks:
      - name: network-10.0.0.0_16
        ipv4_address: "10.0.0.3"
    image: ubuntu-sshd:18.04
    state: started
